//! The catalogue, read out of the other packages' manifests at build time.
//!
//! Every simulation already says what it is, once, in the `description` of its own
//! `Cargo.toml` — that is the line cargo shows, and the line the two README tables carry. So
//! the viewer does not get its own copy to fall out of date: it reads them where they are
//! written and compiles the result in. Add a simulation and it appears here with no edit to
//! this crate at all.
//!
//! Compiled in rather than read at runtime because the viewer has to work as a downloaded
//! executable with no source tree anywhere near it, which is the same reason the assets are.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    // `fulcrum/`, which is this package's parent: the family of simulations.
    let family = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("fulcrum/_viewer has a parent")
        .to_path_buf();

    let mut found: Vec<(String, String)> = Vec::new();
    let mut entries: Vec<_> = std::fs::read_dir(&family)
        .expect("fulcrum/ is readable")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .collect();
    entries.sort();

    for path in entries {
        let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        // Not itself, and nothing that is not a package.
        if name.starts_with('_') || !path.is_dir() {
            continue;
        }
        let manifest = path.join("Cargo.toml");
        let Ok(text) = std::fs::read_to_string(&manifest) else {
            continue;
        };
        println!("cargo:rerun-if-changed={}", manifest.display());
        if let Some(about) = description(&text) {
            found.push((name.to_string(), about));
        }
    }
    println!("cargo:rerun-if-changed={}", family.display());

    let mut out = String::from(
        "/// Every simulation in the set, in the order a directory listing shows them.\n\
         ///\n\
         /// Generated by `build.rs` from each package's own `Cargo.toml`, so there is exactly\n\
         /// one place a description is written.\n\
         pub const CATALOGUE: &[Piece] = &[\n",
    );
    for (name, about) in &found {
        writeln!(out, "    Piece {{ name: {name:?}, about: {about:?} }},")
            .expect("writing to a String");
    }
    out.push_str("];\n");

    let target =
        Path::new(&std::env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("catalogue.rs");
    std::fs::write(&target, out).expect("writing the catalogue");
}

/// The `description` field of a manifest, if it has one on a line of its own — which is how
/// every manifest in this repository is written.
fn description(manifest: &str) -> Option<String> {
    for line in manifest.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("description") else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(rest) = rest.strip_prefix('=') else {
            continue;
        };
        let rest = rest.trim();
        // Only a plain double-quoted string, which is all any of these use. Anything else is
        // skipped rather than guessed at.
        let inner = rest.strip_prefix('"')?.strip_suffix('"')?;
        return Some(inner.replace("\\\"", "\""));
    }
    None
}
